name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (root)
        run: npm install

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Install start-server-and-test
        run: npm install --save-dev start-server-and-test

      - name: Run Cypress tests
        run: npx start-server-and-test "npm run dev --prefix frontend" http://localhost:5173 npm run cypress:run