name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (root)
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start Vite server in background
        run: |
          cd frontend
          nohup npm run dev > vite.log 2>&1 &
          # Odotetaan että palvelin käynnistyy (voit säätää aikaa)
          sleep 10

      - name: Run Cypress tests
        run: npm run cypress:run
