name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            frontend/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules

      - name: Cache Cypress binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Fix Cypress Permissions
        run: chmod +x ./node_modules/.bin/cypress

      - name: Fix wait-on Permissions
        run: chmod +x ./node_modules/.bin/wait-on

      - name: Install Cypress
        run: npx cypress install

      - name: Start frontend server
        run: |
          cd frontend
          npm run dev &
        env:
          CI: true

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npm run cypress:run
        
      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Debug Cypress Results
        run: |
            echo "Debugging Cypress Results:"
            ls -al cypress/results || echo "No results directory found."

      - name: Validate Cypress test results
        run: |
            if [ ! -d cypress/results ] || [ -z "$(ls -A cypress/results/*.json 2>/dev/null)" ]; then
            echo "No Cypress test results found or files are empty."
            exit 1
            fi
            for file in cypress/results/*.json; do
                if ! cat "$file" | jq empty; then
                    echo "Invalid JSON in $file. Check the test reporter configuration."
                    exit 1
                fi
            done

      - name: Fix mochawesome-merge Permissions
        run: chmod +x ./node_modules/.bin/mochawesome-merge

      - name: Generate HTML report        
        run: |
          mkdir -p cypress/results
          npm run report